
# Admin Configuration
[admin]
default_email = "entremotivator@gmail.com"
default_password = "admin123"

# App Configuration
[app]
title = "UserFlow Pro - User Management Toolkit"
page_icon = "🚀"
layout = "wide"

