SUPABASE_URL = "https://your-project.supabase.co"
SUPABASE_ANON_KEY = "your-anon-key"
SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"
ADMIN_EMAIL = "admin@example.com"
ADMIN_PASSWORD = "your-admin-password"


# Admin Configuration
[admin]
default_email = "entremotivator@gmail.com"
default_password = "admin123"

# App Configuration
[app]
title = "UserFlow Pro - User Management Toolkit"
page_icon = "🚀"
layout = "wide"

