# Supabase Configuration
[supabase]
url = "https://ejvzdfnspcwcazltweig.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdnpkZm5zcGN3Y2F6bHR3ZWlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NjM5NjQsImV4cCI6MjA3MzAzOTk2NH0.Qga-V6HVc5kpnTlTraxxO6fxvQEfTYGDFeDWhKNbobU"
service_role_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqdnpkZm5zcGN3Y2F6bHR3ZWlnIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NzQ2Mzk2NCwiZXhwIjoyMDczMDM5OTY0fQ.DA9Rs6TylEMAJNr5kDCt6l_UwM2hSupnZDrmSlf2ogs"

# Admin Configuration
[admin]
default_email = "entremotivator@gmail.com"
default_password = "admin123"

# App Configuration
[app]
title = "UserFlow Pro - User Management Toolkit"
page_icon = "🚀"
layout = "wide"

# Email Configuration (optional)
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_user = "your-email@gmail.com"
email_password = "your-app-password"

